language: go
os:
  - linux
  - osx
go:
  - "go1.13"
go_import_path: github.com/wildbeavers/schema-registry

env:
  global:
    - GOCACHE=off
install:
  - go get ./...
script:
  - go test -v -cover ./...